# Generated by Django 3.1.5 on 2021-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210514_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
